#* This file should be replaced with a good go test
@host = localhost:8000/api/books
@json = application/json

### GET ALL BOOKS
GET http://{{host}} HTTP/1.1

### GET ONE BOOK
GET http://{{host}}/1 HTTP/1.1

### POST A NEW BOOK
POST http://{{host}} HTTP/1.1
content-type: {{json}}

{
    "title": "The sacred bible",
    "isbn": "891238781",
    "AuthorID": 1
}

### UPDATE (PUT) A BOOK
PUT http://{{host}}/1 HTTP/1.1
Content-Type: {{json}}

{
    "title": "The Awnful Bible",
    "isbn": "19881399128"
}

### DELETE A BOOK
DELETE http://{{host}}/2 HTTP/1.1

### GET ALL BOOKS
GET http://{{host}} HTTP/1.1